export default {
    TEXT_FIELD: 'TEXT_FIELD',
    NUMBER_FIELD: 'NUMBER_FIELD',
    SWITCH_FIELD: 'SWITCH_FIELD',
    COLOR_PICKER: 'COLOR_PICKER',
    SINGLE_SELECT_FIELD: 'SINGLE_SELECT_FIELD',
    MULTI_SELECT_FIELD: 'MULTI_SELECT_FIELD' 
}