const authActions = {
    LOGIN_END_SUCCESFULY: 'LOGIN_END_SUCCESFULY',
    LOGIN_SUCCES: 'LOGIN_SUCCES',
    
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCES: 'LOGOUT_SUCCES'
};

export default authActions;